version: '3'

services:
  apache:
    container_name: 'ssl_apache'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html/
      - ./ssl.conf:/etc/apache2/sites-available/ssl.conf
      - ./entrypoint.sh:/opt/entrypoint.sh
    build:
      context: .
      dockerfile: ./Dockerfile
